// Generated by CoffeeScript 1.9.1
(function() {
  var bind,
    slice = [].slice;

  bind = function() {
    var args, func, me, rest;
    func = arguments[0], me = arguments[1], args = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    rest = args;
    return func.call(me, rest);
  };

  Function.prototype.bind = function() {
    var args, func, me;
    func = arguments[0], me = arguments[1], args = 3 <= arguments.length ? slice.call(arguments, 2) : [];
  };

}).call(this);

//# sourceMappingURL=functionBind.js.map
